### ISSUE TITLE
Incorrect image observations when multiple image modalities are requested

### ISSUE THREAD

**Issue by RachithP** [isl-org/spear#267]
Thanks to @quentin-leboutet for reporting this issue.

I'm just making a note of this issue on behalf of Quentin.

- Issue exists in v0.4.0 release.
- This can be reproduced with the `generate_image_dataset` example.

Steps to reproduce:
- Use multiple image modalities in your `user_config.yaml`, for eg., your config file should look something like this
```yaml
SIMULATION_CONTROLLER:
  CAMERA_AGENT:
    CAMERA:
      RENDER_PASSES: ["depth", "normal"] # "depth", "final_color", "normal", "segmentation"
```
- Run `generate_images.py`, and you can see incorrect image observations. Example of incorrect images is below

| Incorrect | Correct |
| ------------- | ------------- |
| ![](https://github.com/isl-org/spear/assets/42787281/46134c55-763c-4fa7-9297-6bbf8156adf7) | ![](https://github.com/isl-org/spear/assets/42787281/cb20b720-b60a-438c-9005-80d2bc7d2236) |
| ![](https://github.com/isl-org/spear/assets/42787281/73595324-ecca-430d-973c-aeaa994073c5) | ![](https://github.com/isl-org/spear/assets/42787281/70a2f259-c4c9-42d6-b924-cfd908668d43) |
